name: "NG"
numeric:
  iPad:
    floating: "numericPortrait"
    landscape: "iPadNumericLandscape"
    portrait: "iPadNumericPortrait"
  iPhone:
    landscape: "numericLandscape"
    portrait: "numericPortrait"
pinyin:
  iPad:
    floating: "pinyinPortrait"
    landscape: "iPadPinyinLandscape"
    portrait: "iPadPinyinPortrait"
  iPhone:
    landscape: "pinyinLandscape"
    portrait: "pinyinPortrait"
symbolic:
  iPad:
    floating: "symbolicPortrait"
    landscape: "iPadPinyinLandscape"
    portrait: "iPadPinyinPortrait"
  iPhone:
    landscape: "symbolicLandscape"
    portrait: "symbolicPortrait"
